"""Loader for the checked-in 25-flop benchmark fixture (impl doc §3 Slice D).

``benchmarks/flops25.json`` is generated by ``scripts/gen_flops25.py`` and
checked in; tests and solves LOAD it, they never regenerate it. It pins the
BTNopen_BBcall 40bb spot: fixed preflop ranges (fixture constants), pot,
effective stack, and the 33/75/125%+jam bet grid.

Postflop the **BB is out of position** (acts first) and the **BTN is in
position** — so in solver terms player 0 (OOP) = BB, player 1 (IP) = BTN.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import numpy as np

from pokerlab.engine.cards import card_from_str
from pokerlab.solver import subgame as sg

FIXTURE_PATH = Path(__file__).resolve().parents[3] / "benchmarks" / "flops25.json"


@lru_cache(maxsize=1)
def load_flops25(path: str | None = None) -> dict:
    p = Path(path) if path else FIXTURE_PATH
    if not p.exists():
        raise FileNotFoundError(
            f"flops25 fixture missing: {p}\n"
            "generate it with: uv run python scripts/gen_flops25.py"
        )
    return json.loads(p.read_text())


def _cards(s: str) -> tuple[int, ...]:
    return tuple(card_from_str(s[i:i + 2]) for i in range(0, len(s), 2))


def range_vectors(fixture: dict | None = None) -> tuple[np.ndarray, np.ndarray]:
    """(oop=BB, ip=BTN) full 1326 combo-weight vectors for the fixture ranges."""
    fx = fixture or load_flops25()
    bb = sg.range_from_classes({c: 1.0 for c in fx["ranges"]["BB"]})
    btn = sg.range_from_classes({c: 1.0 for c in fx["ranges"]["BTN"]})
    return bb, btn


def build_solver(entry: dict, cfg: sg.BetConfig | None = None,
                 fixture: dict | None = None) -> sg.SubgameSolver:
    """Build a ready-to-iterate solver for one flops25 ``entry`` (a flop dict)."""
    fx = fixture or load_flops25()
    board = _cards(entry["cards"])
    oop, ip = range_vectors(fx)
    tree = sg.build_tree(board, pot0=fx["meta"]["pot_bb"],
                         stack=fx["meta"]["eff_stack_bb"], cfg=cfg)
    return sg.SubgameSolver(tree, board, oop, ip, pot0=fx["meta"]["pot_bb"])
