"""PBS value network for Leduc ReBeL (plan §7 L3; impl doc §3 Slice G).

A small torch MLP approximating the public-belief-state value function: it maps
PBS features (pot one-hot + both reach vectors, 15 dims) to per-card
counterfactual values for both players (2×6 = 12 outputs). The training target is
the *equilibrium* value of the round-2 subgame at that belief — self-generated by
`resolve_round2` (no vendor data), sampled at reach-perturbed (off-equilibrium)
beliefs so the net generalizes across the belief simplex, per ReBeL.

Determinism: CPU + fixed seeds by default (MPS is available but its reductions are
nondeterministic across runs; the CI bar wants a reproducible number). The device
is selectable for the training script.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import torch
from torch import nn

from .pbs import LEAF_LINES, NUM_CARDS, PBS

FEAT_DIM = len(LEAF_LINES) + 2 * NUM_CARDS   # 5 + 12 = 17
OUT_DIM = 2 * NUM_CARDS                       # 12


def seed_everything(seed: int = 0) -> None:
    torch.manual_seed(seed)
    np.random.seed(seed)


class PBSValueNet(nn.Module):
    """Small MLP: PBS features -> (2,6) per-card counterfactual values."""

    def __init__(self, hidden: int = 64):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(FEAT_DIM, hidden), nn.ReLU(),
            nn.Linear(hidden, hidden), nn.ReLU(),
            nn.Linear(hidden, OUT_DIM),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


@dataclass
class TrainReport:
    final_loss: float
    val_rmse: float
    n_train: int
    epochs: int
    device: str


def train_valuenet(features: np.ndarray, targets: np.ndarray, *,
                   hidden: int = 64, epochs: int = 400, lr: float = 1e-3,
                   batch: int = 256, seed: int = 0, device: str = "cpu",
                   val_frac: float = 0.2) -> tuple[PBSValueNet, TrainReport]:
    """Train the value net on (features, targets); return net + a report."""
    seed_everything(seed)
    dev = torch.device(device)
    x = torch.as_tensor(features, dtype=torch.float32, device=dev)
    y = torch.as_tensor(targets, dtype=torch.float32, device=dev)

    n = x.shape[0]
    n_val = max(1, int(n * val_frac))
    perm = torch.randperm(n, generator=torch.Generator().manual_seed(seed))
    val_idx, tr_idx = perm[:n_val], perm[n_val:]
    xt, yt = x[tr_idx], y[tr_idx]
    xv, yv = x[val_idx], y[val_idx]

    net = PBSValueNet(hidden).to(dev)
    opt = torch.optim.Adam(net.parameters(), lr=lr)
    loss_fn = nn.MSELoss()
    gen = torch.Generator().manual_seed(seed + 1)

    last = float("nan")
    for _ in range(epochs):
        order = torch.randperm(xt.shape[0], generator=gen)
        for i in range(0, xt.shape[0], batch):
            sel = order[i:i + batch]
            opt.zero_grad()
            loss = loss_fn(net(xt[sel]), yt[sel])
            loss.backward()
            opt.step()
        last = float(loss.item())

    net.eval()
    with torch.no_grad():
        val_rmse = float(torch.sqrt(loss_fn(net(xv), yv)).item())
    return net, TrainReport(last, val_rmse, int(xt.shape[0]), epochs, str(dev))


def net_leaf_value_fn(net: PBSValueNet, *, device: str = "cpu"):
    """Wrap a trained net as a trunk/agent leaf-value fn: (contrib,bets,r0,r1)->(2,6)."""
    dev = torch.device(device)
    net = net.to(dev).eval()

    def leaf_fn(contrib, bets, r0, r1) -> np.ndarray:
        pbs = PBS(public_card=None, bets=tuple(bets), contrib=tuple(contrib),
                  reach=np.stack([np.asarray(r0, float), np.asarray(r1, float)]))
        feats = torch.as_tensor(pbs.features(), dtype=torch.float32, device=dev)
        with torch.no_grad():
            out = net(feats).cpu().numpy()
        return out.reshape(2, NUM_CARDS)

    return leaf_fn
